### ISSUE TITLE
background-image

### ISSUE THREAD

**Issue by milad-abujarada** [den-materials/design-and-css-challenge-lab#10]
The backgound-image property not working for me.

**Comment by ZebGirouard** [comment]
Hi @milad-abujarada , take a look in developer tools, and make sure the following is happening:

1) The image url is actually an image (copy it into the URL bar in your browser)
2) The image is being applied to something
3) The image is being applied to the whole background

One or more of these things is probably breaking, and when you find out which one, an answer may reveal itself.  If not, you can bring it to Tyler right after class today.
