### ISSUE TITLE
Relaxr/Google Font

### ISSUE THREAD

**Issue by mattsteffey** [den-materials/design-and-css-challenge-lab#2]
Couldn't get the Google font to work on my page. Holler.

**Comment by mrkrosenberg** [comment]
did you try activating it in css with "font-family: "Open Sans";?

**Comment by brianpbyers** [comment]
If you only download 'Open Sans' it just gives you the 400 font size.  Before you link the font you've got to 'customize it' to select the weights, then switch over the to the embed side.

**Comment by mattsteffey** [comment]
I used the custom weights and activated it in CSS with the font-family. 

When I did the CSS side I used -

body {
  font-family: 'Open Sans', sans-serif;
}

-----------

The link I used in the HTML side was -

<link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,600,600i,800" rel="stylesheet">

**Comment by joldenb** [comment]
@mattsteffey for some reason I don't see the HTML you used, it should be something like this right? <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

**Comment by joldenb** [comment]
hey! It didnt show up in mine either
 try this:
`<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`

**Comment by ZebGirouard** [comment]
@JinTak noticed that Chrome will try to "guess" at the font if you don't explicitly import it.  But the best way to get it in is definitely the method that @anhonestmouse is recommending.
