### ISSUE TITLE
pushing to GitHub

### ISSUE THREAD

**Issue by rjmcbain** [den-materials/design-and-css-challenge-lab#4]
I am having an issue pushing my relaxr lab files to my repo. 

i keep getting this error:
Please make sure you have the correct access rights
and the repository exists.

**Comment by joldenb** [comment]
Hey @rjmcbain here are the debugging steps we've taken with some other folks in class to solve this:
1. Follow the steps at the following link to determine if you have an SSH key and if you have uploaded that key to your account on GitHub. https://help.github.com/articles/checking-for-existing-ssh-keys/
2. Verify that the git project on your laptop is trying to connect to the correct repo on GitHub. Do a "git remove -v" on the command line in your project, and see if the URL listed there matches the URL in GitHub where you're trying to connect.  If it's not, try  "git remote set-url origin <THE CORRECT URL>"
Try these and let me know if it still doesn't work.
