### ISSUE TITLE
Google italic font

### ISSUE THREAD

**Issue by w-smith** [den-materials/design-and-css-challenge-lab#6]
I couldn't figure out how to get the italic version of the google font to work. When using the font weight '300i'. I ended up cheating and using 'font-style: italic;'.

**Comment by middtown** [comment]
yeah! whats up with that?

**Comment by mrkrosenberg** [comment]
that's what I did as well. I messed with it for a while but couldn't figure it out.

**Comment by brianpbyers** [comment]
Could anyone pull the '300i' option out without doing this?

**Comment by ZebGirouard** [comment]
I think I might be putting this together... @w-smith , I don't think that's cheating.  That's exactly what you need to do.  The import just imports those versions of the font.  You need to explicitly set `font-style: italic;` to get it to show up.  I am not sure if this is part of the confusion, but note that `font-weight` is only for thickness of text and `font-style` controls `italic` vs non-italic.  I think everyone on this thread just did the right thing.

@anhonestmouse @middtown @mrkrosenberg

**Comment by ZebGirouard** [comment]
Yupyup, looks like that was the issue--as I mentioned, I've struggled through this too.  Getting nostalgic :)
