### ISSUE TITLE
Image manipulation

### ISSUE THREAD

**Issue by rickytranmer** [den-materials/design-and-css-challenge-lab#8]
I was having trouble manipulating images, mainly resizing images while still keeping the aspect ratio.  Any useful bookmarks?

**Comment by mattsteffey** [comment]
Look at the image file and check the dimensions.

So if you have a file that's 200x300, then you can use pen and paper math to scale it up. like if you want to increase the size by 50%, then you can do;

200 x 1.5 = 300
300 . 1.5 = 450

you would just set - 
width: 300;
height: 450;


hope this helps.

**Comment by ZebGirouard** [comment]
@rickytranmer , `width: auto` and `height: auto` might help you with this, depending on which (height or width) you need to constrain, the other one will just match the aspect ratio `auto`matically.  In fact, this is the default setting.  Another thing I'd look at is `max-width` and/or `max-height`.  If you have a ton of differently-sized images, this makes your life a lot easier.

We will talk about ways (namely, Sass) to do this with variables like @mattsteffey is recommending in the next unit.  In the end, though, if you try to set explicit height AND width for an image, and it doesn't match the aspect ratio, it simply will stretch or squish, that's what the browser does (basically, "really? you want these skis to go inside that cube-shaped box?  OK, here we go...")
